# Generated by Django 5.0.6 on 2024-06-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=100)),
                ('EmpName', models.CharField(max_length=150)),
                ('Department', models.CharField(max_length=150)),
                ('MobileNo', models.IntegerField()),
                ('ProductName', models.CharField(max_length=150)),
                ('ProductType', models.CharField(max_length=150)),
                ('ProductImage', models.ImageField(upload_to='media/assetshare/images/')),
                ('ProductDesc', models.TextField(max_length=255)),
                ('ProductCount', models.IntegerField()),
            ],
        ),
    ]
