# Generated by Django 5.0.6 on 2024-06-10 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=150)),
                ('MobileNo', models.IntegerField()),
                ('Product_count', models.IntegerField()),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.item')),
            ],
        ),
    ]
