# Generated by Django 5.0.6 on 2024-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='EmpID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='EmpName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ProductName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='ProductType',
            field=models.CharField(max_length=255),
        ),
    ]
