# Generated by Django 5.0.6 on 2024-06-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_remove_item_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interested',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
