# Generated by Django 5.0.6 on 2024-06-10 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0009_delete_interested_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=255)),
                ('EmpName', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('MobileNo', models.IntegerField()),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductType', models.CharField(max_length=255)),
                ('ProductDesc', models.TextField(max_length=255)),
                ('ProductCount', models.IntegerField()),
                ('ProductImage', models.ImageField(upload_to='media/assetshare/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=150)),
                ('MobileNo', models.IntegerField()),
                ('Product_count', models.IntegerField()),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.item')),
            ],
        ),
    ]
