# Generated by Django 5.0.6 on 2024-06-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_item_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
