# Generated by Django 5.0.6 on 2024-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_alter_interested_created_alter_item_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admincred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
    ]
