# Generated by Django 5.0.6 on 2024-06-13 02:55

import asset.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_admincred'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_id', models.CharField(max_length=100)),
                ('hod_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dept1_Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_id', models.CharField(max_length=100)),
                ('hod_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dept2_Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_id', models.CharField(max_length=100)),
                ('hod_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=150)),
                ('MobileNo', models.IntegerField()),
                ('Product_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=255)),
                ('EmpName', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('MobileNo', models.IntegerField()),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductType', models.CharField(max_length=255)),
                ('FinanceType', models.CharField(max_length=255)),
                ('ProductDesc', models.TextField(max_length=255)),
                ('ProductCount', models.IntegerField()),
                ('ProductImage', models.ImageField(upload_to='media/assetshare/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), asset.models.validate_image_size])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=150)),
                ('MobileNo', models.IntegerField()),
                ('Product_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.post_item')),
            ],
        ),
        migrations.CreateModel(
            name='Request_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=255)),
                ('EmpName', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('MobileNo', models.IntegerField()),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductType', models.CharField(max_length=255)),
                ('FinanceType', models.CharField(max_length=255)),
                ('ProductDesc', models.TextField(max_length=255)),
                ('ProductCount', models.IntegerField()),
                ('ProductImage', models.ImageField(upload_to='media/assetshare/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), asset.models.validate_image_size])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Admincred',
        ),
        migrations.AddField(
            model_name='post_interest',
            name='Item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.post_item'),
        ),
        migrations.DeleteModel(
            name='Interested',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
