# Generated by Django 5.0.6 on 2024-06-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_bandf_dept1_hod_dept2_hod_post_interest_post_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_id', models.CharField(max_length=100)),
                ('hod_password', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Dept1_Hod',
        ),
        migrations.DeleteModel(
            name='Dept2_Hod',
        ),
    ]
