# Generated by Django 5.0.6 on 2024-06-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_hod_delete_dept1_hod_delete_dept2_hod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandf',
            old_name='hod_id',
            new_name='BF_id',
        ),
        migrations.RenameField(
            model_name='bandf',
            old_name='hod_password',
            new_name='BF_password',
        ),
        migrations.RenameField(
            model_name='post_interest',
            old_name='Department',
            new_name='Department1',
        ),
        migrations.RenameField(
            model_name='post_interest',
            old_name='EmpID',
            new_name='EmpID1',
        ),
        migrations.RenameField(
            model_name='post_interest',
            old_name='Item_id',
            new_name='Item_id1',
        ),
        migrations.RenameField(
            model_name='post_interest',
            old_name='MobileNo',
            new_name='MobileNo1',
        ),
        migrations.RenameField(
            model_name='post_interest',
            old_name='Product_count',
            new_name='Product_count1',
        ),
        migrations.RenameField(
            model_name='post_interest',
            old_name='created',
            new_name='created1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='Department',
            new_name='Department1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='EmpID',
            new_name='EmpID1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='EmpName',
            new_name='EmpName1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='FinanceType',
            new_name='FinanceType1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='MobileNo',
            new_name='MobileNo1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='ProductCount',
            new_name='ProductCount1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='ProductDesc',
            new_name='ProductDesc1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='ProductImage',
            new_name='ProductImage1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='ProductName',
            new_name='ProductName1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='ProductType',
            new_name='ProductType1',
        ),
        migrations.RenameField(
            model_name='post_item',
            old_name='created',
            new_name='created1',
        ),
    ]
