# Generated by Django 5.0.4 on 2024-06-14 09:32

import asset.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_rename_hod_id_bandf_bf_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=150)),
                ('MobileNo', models.IntegerField()),
                ('Product_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=255)),
                ('EmpName', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('MobileNo', models.IntegerField()),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductType', models.CharField(max_length=255)),
                ('FinanceType', models.CharField(max_length=255)),
                ('ProductDesc', models.TextField(max_length=255)),
                ('ProductCount', models.IntegerField()),
                ('ProductImage', models.ImageField(upload_to='media/assetshare/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), asset.models.validate_image_size])),
                ('Approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post_interest',
            name='Item_id1',
        ),
        migrations.RemoveField(
            model_name='request_interest',
            name='Item_id',
        ),
        migrations.DeleteModel(
            name='Request_Item',
        ),
        migrations.AddField(
            model_name='interest',
            name='Item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.item'),
        ),
        migrations.DeleteModel(
            name='Post_Interest',
        ),
        migrations.DeleteModel(
            name='Post_Item',
        ),
        migrations.DeleteModel(
            name='Request_Interest',
        ),
    ]
