# Generated by Django 5.0.4 on 2024-06-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_interest_item_remove_post_interest_item_id1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='Given',
            field=models.BooleanField(default=False),
        ),
    ]
